# Generated by Django 2.0.5 on 2018-05-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aventuras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fechaInicio', models.DateTimeField()),
                ('fechaInscripcion', models.DateTimeField()),
            ],
        ),
    ]
