# Generated by Django 2.0.5 on 2018-05-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aventuras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='reglamento',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
