# Generated by Django 2.0.5 on 2018-06-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aventuras', '0002_auto_20180529_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
