# Generated by Django 2.0.5 on 2018-06-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aventuras', '0003_evento_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
