# Generated by Django 2.0.5 on 2018-06-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aventuras', '0006_auto_20180605_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='ubicacionLat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ubicacionLng',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
