# Generated by Django 2.0.5 on 2018-07-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aventuras', '0008_auto_20180605_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='ubicacionLat',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='ubicacionLng',
        ),
        migrations.AddField(
            model_name='evento',
            name='recorrido',
            field=models.URLField(blank=True, null=True),
        ),
    ]
