# Generated by Django 2.0.5 on 2018-07-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aventuras', '0010_auto_20180705_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='recorrido',
            field=models.URLField(blank=True, null=True),
        ),
    ]
