# Generated by Django 2.0.5 on 2018-07-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aventuras', '0011_auto_20180705_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='recorrido',
            field=models.URLField(blank=True, default='https://www.google.com/maps/d/u/0/', null=True),
        ),
    ]
