# Generated by Django 2.1 on 2018-08-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aventuras', '0015_auto_20180705_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='recorrido',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
